external-url-prefix: "http://localhost:9000"
keysets:
  testing-ca:
    path-prefix: tests/data/keys
    keys:
      root:
        path: root.key.pem
        password: secret
      signer:
        path: signer.key.pem
        password: secret

pki-architectures:
  testing-ca:
    keyset: testing-ca
    entity-defaults:
      country-name: RU
      organization-name: Testing Authority
    entities:
      root:
        common-name: Root CA
      signer:
        common-name: Alice
    certs:
      root:
        subject: root
        subject-key: root
        issuer: root
        authority-key: root
        validity:
          valid-from: "2000-01-01T00:00:00+0000"
          valid-to: "2500-01-01T00:00:00+0000"
        profiles:  # will auto-populate the CRL distribution points extension for all issued certs
          - id: simple-ca
            params:
              crl-repo: root
      signer:
        issuer: root
        validity:
          valid-from: "2020-01-01T00:00:00+0000"
          valid-to: "2050-01-01T00:00:00+0000"
        extensions:
          - id: key_usage
            critical: true
            smart-value:
              schema: key-usage
              params: [digital_signature, non_repudiation, key_encipherment, data_encipherment]
    services:
      crl-repo:
        root:
          for-issuer: root
          signing-key: root
          simulated-update-schedule: "P90D"
      cert-repo:
        root:
          for-issuer: root
          publish-issued-certs: yes
